#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FileExplorer.Resource", IsApplication=true)]

namespace FileExplorer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int folder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int chkSelected = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int editDir = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int imgIcon = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int listViewFile = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txtName = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layoutFileSystem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ActivityNotFound = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int BATCHREMOVE = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int BackPressAgainToExit = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int ConfirmBatchRemove = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int DirCanNotRead = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int Favorite = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int MKDIR = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int REFRESH = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int Remove = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Rename = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int Warn = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
